/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.js to modify the generation of this file.
module.exports = {
  "sitecoreApiKey": "no-api-key-set",
  "sitecoreApiHost": "http://localhost:3000",
  "jssAppName": "advanced-sitecore",
  "defaultLanguage": "en",
  "graphQLEndpointPath": "/api/advanced-sitecore",
  "graphQLEndpoint": "http://localhost:3000/api/advanced-sitecore?sc_apikey=no-api-key-set"
};
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow
// reloadnow